
theme = "hugo-theme-codex" 

# Override these settings with your own
title = "Lucas Arbiza"
languageCode = "en-us"
baseURL = "https://arbiza.com.br/"
copyright = "Â© {year}"

# Add your Disqus shortname here.
disqusShortname = "lucasarbiza"

# Add your Google Analytics identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  twitter = "https://twitter.com/lucas_arbiza"
  github = "https://github.com/arbiza"
  email = "mailto:lucas@arbiza.com.br"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/lucas.arbiza"
  linkedin = "https://www.linkedin.com/in/lucasarbiza"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  iconOrder = ["LinkedIn", "Email", "GitHub", "Twitter", "Instagram"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "devnetops"
  name = "DevNetOps"
  title = "DevNetOps Etc."
  url = "/blog"


